/**
 * Objeto 'canciones' que contiene una lista de canciones con su información correspondiente: nombre, archivo de audio y letra. Cada canción está indexada
 * por un número único.
 */
const canciones = {
    1: {
        nombre: "Y, Si Fuera Ella!",
        audio: "music/01 - Y, Si Fuera Ella!.mp3",
        letra: "Ella, se desliza y me atropella<br>y, aunque a veces no me importe<br>sé, que el día que la pierda,<br>volveré a sufrir por...<br>Ella, que aparece y se esconde;<br>que se marcha y se queda;<br>que es pregunta y es respuesta;<br>que es mi oscuridad, mi estrella.<br>Ella, me peina el alma y me la enreda;<br>va conmigo pero, no sé donde va.<br>Mi rival, mi compañera;<br>que está tan dentro de mi vida y,<br>a la vez, está tan fuera.<br>Sé que volveré a perderme y,<br>la encontraré de nuevo<br>pero con otro rostro y otro<br>nombre diferente y otro cuerpo.<br>Pero sigue ella, que otra vez me lleva;<br>nunca me responde si, al girar la rueda...<br><br>Ella, se hace fría y se hace eterna;<br>un suspiro en la tormenta,<br>a la que tantas veces le cambió la voz.<br>Gente que va y que viene y, siempre es<br>ella, que me miente y me lo niega;<br>que me olvida y me recuerda<br>pero, si mi boca se equivoca,<br>pero si mi boca se equivoca y,<br>al llamarla nombro a otra,<br>a veces siente compasión por este loco,<br>ciego y loco corazón.<br><br>Sea, lo quiera Dios que sea<br>mi delito es la torpeza de ignorar<br>que hay quien no tiene corazón.<br>Y va quemando, va quemándome y me quema.<br>Y, ¿si fuera ella?<br><br>Ella me peina el alma y me la enreda;<br>va conmigo...digo yo.<br>Mi rival, mi compañera; esa es ella.<br>Pero me cuesta, cuando otro adiós se va tan cerca.<br>Y, la perderé de nuevo. Y otra vez me preguntaré,<br>mientras se va y, no habrá respuesta.<br>Y, si esa se que se aleja...<br>La que estoy perdiendo...<br>Y, ¿si esa era? Y ¿si fuera ella?<br><br>Sea, lo que quiera Dios que sea.<br>Mi delito es la torpeza de ignorar<br>que hay quien no tiene corazón.<br>Y va quemándome y me quema.<br>Y, ¿si fuera ella?<br><br>...a veces siento compasión<br>por este loco, ciego y loco corazón.<br>¿Era? ¿Quién me dice, si era ella?<br>Y, si la vida es una rueda y va girando<br>y nadie sabe cuando tiene que saltar.<br>Y la miro...y, ¿si fuera ella? ¿Si fuera ella?"
    },
    2: {
        nombre: "Ese Último Momento ",
        audio: "music/02 - Ese Último Momento.mp3",
        letra: "Ahora que tengo la ocasión, quiero que hablemos los dos<br>tú de mí, yo de tí, del corazón que sí<br>que nunca es bueno el momento, hasta que no hay otra opción,<br>siempre es el mismo cuento...<br>ese último momento.<br>Ahora que tengo la oportunidad la tengamos o no<br>nos callaremos los dos, tu por mí, yo por tí, por no enredar ya ves<br>porque será que lo hacemos incluso viendo llegar<br>ese último momento no cuando no queda tiempo<br>para decir siquiera: te voy a echar de menos<br>Si vas a irte vete, pero no te despidas<br>sal de noche, sal a oscuras,<br>sal descalza y de puntillas niña vete, vete y cierra la puerta<br>que no quiero verte salir de mi vida.<br>No más plazos aplazables, si ha de ser así adelante<br>y mejor este momento déjalo para algún otro instante<br>acabemos cuanto antes nadie tiene que arrastrarse<br>ese último momento vívelo, y los demás,<br>los demás que aguanten, y los demás que aguanten.<br>Ahora no tengo la ocasión, no la tengo que no<br>que más da ya pasó, cuanto lamento que al final<br>no hablásemos ninguno de los dos porque<br>ahora nos sobra tiempo, para pensar qué pasó<br>ese último momento cuando no tuve tiempo, ni tú<br>para escribir unos versos de cuando aquellos besos.<br>Si estás oyendo vuelve, ni siquiera saludes<br>con la luz de la mañana abre puertas a patadas<br>niña vuelve, que no hacen falta razones<br>me muero por verte, volver a tenerte.<br>No mas dudas razonables, para mi no es comparable,<br>ese último momento me robó<br>el milagro de tenerte a cada instante<br>acabemos cuanto antes, con un siglo abrá bastante<br>este último momento es de los dos<br>y los demás, los demás que aguanten<br>No mas dudas razonables, para mi no es comparable"
    },
    3: {
        nombre: "Corazón Partío!",
        audio: "music/03 - Corazón Partío.mp3",
        letra: "Tiritas pa este corazón partío,<br>tiri-ti-tando de frío.<br>Tiritas pa este corazón partío<br>pa este corazón.<br><br>Ya lo ves, que no hay dos sin tres,<br>que la vida va y viene y que no se detiene...<br>y, qué sé yo,<br>pero miénteme aunque sea, dime que algo queda<br>entre nosotros dos, que en tu habitación<br>nunca sale el sol, no existe el tiempo,<br>ni el dolor.<br><br>Llévame si quieres a perder,<br>a ningún destino, sin ningún por qué.<br><br>Ya lo sé, que corazón que no ve<br>es corazón que no siente,<br>o corazón que te miente amor.<br>Pero, sabes que en lo más profundo de mi alma<br>sigue aquel dolor por creer en ti.<br>¿Qué fue de la ilusión y de lo bello que es vivir?<br><br>Para qué me curaste cuando estaba hería<br>si hoy me dejas de nuevo el corazón partío.<br><br>¿Quién me va a entregar sus emociones?<br>¿Quién me va a pedir que nunca le abandone?<br>¿Quién me tapará esta noche si hace frío?<br>¿Quién me va a curar el corazón partío?<br>¿Quién llenará de primaveras este enero,<br>y bajará la luna para que juguemos?<br>Dime, si tú te vas, dime cariño mío,<br>¿quién me va a curar el corazón partío?<br><br>Tiritas pa este corazón partío<br>Tiritas pa este corazón partío.<br><br>Dar solamente aquello que te sobra<br>nunca fue compartir, sino dar limosna, amor<br>si no lo sabes tú, te lo digo yo.<br>Después de la tormenta siempre llega la calma,<br>pero, sé que después de ti,<br>después de ti no hay nada.<br><br>Para qué me curaste cuando estaba hería<br>si hoy me dejas de nuevo el corazón partío.<br><br>¿Quién me va a entregar sus emociones?<br>¿Quién me va a pedir que nunca le abandone?<br>¿Quién me tapará esta noche si hace frío?<br>¿Quién me va a curar el corazón partío?<br>¿Quién llenará de primaveras este enero,<br>y bajará la luna para que juguemos?<br>Dime, si tú te vas, dime, cariño mío<br>¿Quién me va a curar el corazón partío?<br><br>¿Quién me va a entregar..."
    },
    4: {
        nombre: "Siempre Es de Noche",
        audio: "music/04 - Siempre Es de Noche.mp3",
        letra: "Cuéntame cómo va cayendo el sol<br>Mientras hablas pensaré<br>Qué guapa estás, qué suerte ser<br>La mitad del cuento de un atardecer<br>Que observo al escucharte,<br>porque mis ojos son tu voz<br>Acércate, que cuando estemos piel con piel,<br>mis manos te dibujarán,<br>tu aroma me dirá tu edad.<br>Junto a ti, unidos sin saber por qué,<br>seguramente se me note<br>el resplandor de una ilusión,<br>porque a tu lado puedo olvidar.<br>Que para mí siempre es de noche,<br>pero esta noche es como un atardecer,<br>si logras que a la vida me asome,<br>tus ojos sean los que brillen.<br>Y la luna que la borren,<br>que en mi eterna oscuridad<br>El cielo tiene nombre: tu nombre.<br>Que no daría yo por contemplarte<br>aunque fuera un sólo instante.<br>Hace frío. Es tarde y tienes que volver,<br>que hay alguien que te espera, seguro.<br>Una vez más el tiempo se nos fue.<br>¿Volverás? Dime si mañana volverás<br>como lo has hecho cada tarde,<br>para contarme cómo muere el día<br>Y se marchó. Ella se alejó de él.<br>Pero, como en las cartas... dos puntos, posdata,<br>se me olvidaba, no me presenté.<br>Sólo fui testigo por casualidad,<br>hasta que de pronto, él me pregunto:<br>era bella, ¿no es verdad?<br>más que la luna -dije yo-, Y él sonrió.<br>Nunca más se hará reproches<br>por intentar amanecer.<br>No volverá a perderse en la noche,<br>porque su alma hoy brilla con más fuerza<br>que un millón de soles.<br>Pero, en su eterna oscuridad,<br>a veces se le oye a voces:<br>qué no daría yo por contemplarte,<br>Aunque fuera un sólo instante<br>...por intentar amanecer.<br>No volverá a perderse en la noche,<br>porque su alma hoy brilla con más fuerza<br>que un millón de soles.<br>Pero en su eterna oscuridad,<br>a veces se le oye a voces:<br>qué no daría yo por contemplarte,<br>aunque fuera un sólo instante<br>Qué no daría yo por contemplarte,<br>aunque fuera un sólo instante"
    },
    5: {
        nombre: "La margarita dijo no Alejandro",
        audio: "music/05 - La margarita dijo no Alejandro.mp3",
        letra: "Bajo la lluvia y bajo el sol,<br>la margarita dijo no.<br>Bajo la lluvia y bajo el sol,<br>la margarita dijo no.<br>Bajo la lluvia y bajo el sol,<br>bellos e inmóviles, los dos<br>se prometieron no crecer.<br>No sé por qué, me convenció<br>hace tanto de aquello...<br>Bajó la Luna y les habló:<br>para volver, la condición<br>es que hay que transformarse en ola<br>y no dejar tu orilla sola,<br>ni siquiera un momento.<br>Pero les pudo la ambición:<br>él quiso acariciar la Luna;<br>ella, ser rosa y amapola.<br>Y esperando visita,<br>deshojé margaritas.<br>Pasaron los años y ella se marchitó<br>deshojando fantasías.<br>El niño se hizo mayor.<br>No han vuelto a verse en la vida.<br>La margarita dijo no.<br>La margarita dijo no.<br>Pasaron los años y ella se marchitó<br>deshojando fantasías.<br>El niño se hizo mayor.<br>No han vuelto a verse en la vida.<br>La margarita dijo no.<br>La margarita dijo no.<br>Bajo la lluvia y bajo el sol,<br>la margarita dijo no.<br>Bajo la lluvia y bajo el sol,<br>la margarita dijo no.<br>Si bajas, Luna, escúchame y escucha tú esta vez:<br>para volver, la condición<br>es que aprendamos a crecer,<br>sin que caduque la pasión,<br>aunque no me arrepiento.<br>Sin que nos gane la ambición.<br>Yo quise acariciar la Luna<br>y ella, ser rosa y amapola.<br>Y, esperando visita, otra vez,<br>Deshojó margaritas.<br>Pasaron los años y ella se marchitó<br>deshojando fantasías.<br>El niño se hizo mayor.<br>No han vuelto a verse en la vida.<br>La margarita dijo no.<br>La margarita dijo no.<br>Pasaron los años y ella se marchitó<br>deshojando fantasías.<br>El niño se hizo mayor.<br>No han vuelto a verse en la vida.<br>La margarita dijo no.<br>La margarita dijo no.<br>Bajo la lluvia y bajo el sol,<br>la margarita dijo no.<br>Bajo la lluvia y bajo el sol,<br>la margarita dijo no.<br>Qué extraño es esto del amor,<br>¿por qué preguntan a una flor?<br>Bajo la lluvia y bajo el Sol,<br>la margarita dijo no."
    },
    6: {
        nombre: "Hoy Que No Estás",
        audio: "music/06 - Hoy Que No Estás.mp3",
        letra: "Hoy que no estás, el mundo se ha vestido de gris;<br>de pena, el cielo se va llorando por el jardín.<br>Hoy que no estás, mi cama no ha podido dormir.<br>Hoy que no estás, las calles son inútiles.<br>O son el eco de tu risa, o son inútiles.<br>Hoy que no estás, te extraña mi guitarra:<br>mi perro está triste; se ausenta la magia, niña.<br>Si no puedo verte, no quiero paisajes.<br>Si no me acompañas, ¿dónde voy a ir?<br>Si no podré volver jamás a acariciarte,<br>seré como una orilla sin mar, sin oleaje y brisa.<br>Me dirá que sí, me dirá que sí.<br>Me quedará en el aire un pensamiento,<br>que se irá sincero y lento,<br>y en el viento flotará, hoy que no estás.<br>Y que a pesar que me parece hasta mentira,<br>puede que la vida siga.<br>Pero si tu no estás... ¿Pa' qué?<br>Y que a pesar que me parece hasta mentira,<br>puede que la vida siga.<br>Pero si tu no estás ¿pa' qué?<br>Dime, ¿pa' qué?<br>Hoy que no estás, voy a inventarme el final:<br>tú regresabas y no nos separábamos más<br>es mi canción; no tengo que decir la verdad.<br>Diré que me besas y, al darte la mano,<br>oiremos violines y atardecerá.<br>Así cuando me entere que no estás aquí,<br>al menos, mi canción me dirá que sí.<br>Me dirá que sí, me dirá que sí, que te quedes.<br>Y quedará solamente un pensamiento,<br>que también se irá. Y te cuento<br>que, en el viento flotará, hoy que no estás.<br>Y que a pesar que me parece hasta mentira,<br>puede que la vida siga.<br>Pero si tu no estás, ¿pa qué?<br>Y quedará solamente un pensamiento,<br>que se irá sincero y lento,<br>y en el viento flotará, hoy que no estás.<br>Y que a pesar que me parece hasta mentira,<br>puede que la vida siga.<br>Pero si tu no estás...¿pa qué?<br>Y que a pesar que me parece hasta mentira,<br>puede que la vida siga.<br>Pero si tú no estás,... ¿pa qué?<br>Dime, ¿pa qué?<br>Hoy que no estás. Dime, ¿pa qué?<br>Dirá que si te quedas...<br>Me dirá que sí, me dirá que sí.<br>Me dirá que sí, me dirá que sí."
    },
    7: {
        nombre: "Un Charquito de Estrellas",
        audio: "music/07 - Un Charquito de Estrellas.mp3",
        letra: "Naufragué en un charquito de estrellas.<br>Yo solo quería navegar, poner mis ganas por velas.<br>Y, el mar llené llorando por ella<br>un sueño anclado en la luna.<br>No pude ver orilla ningúna y, normal<br>que naufragase a su vera<br>entre la espuma que acaricia y atropella<br>como un verso del poema que escribí,<br>se van borrando tus huellas.<br>Mi ilusión es la cometa que se eleva<br>y que se estrella contra mí, contra mí, contra mí.<br>¿Dónde están los mares de verdad, gálidos?<br>Y aquella brisa que apagaba poco a poco el sol,<br>¿dónde quedó? las noches mágicas ¿te acuerdas?<br>de charquitos y de estrellas.<br>Esta noche iba a brillar la luna,<br>pero la tormenta la asustó.<br>Mañana, cuando salga el sol<br>se reirá de ella, pero de nosotros no.<br>Esta noche hay miles de estrellas<br>y una mágica y radiante luna llena.<br>Y aquel charquito de estrellas<br>resultó ser un desierto:<br>solo un espejismo de arena y de sal,<br>de risas hoy verdaderas.<br>Suelta velas y verás mi cometa<br>que se eleva y que se va, que se va, que se va.<br>¿Dónde están los sueños de verdad, cálidos?<br>y las tormentas de caricias,<br>donde el huracán, amándonos.<br>La noche es grande y es eterna<br>ya no hay charcos; solo estrellas.<br>Esta noche brillará la luna,<br>porque la tormenta es nuestro amor, amor amor.<br>Mañana, cuando salga el sol, llorará de envidia<br>por ella y por lo que pasó.<br>Esta noche hay miles de estrellas<br>y una mágica y radiante Luna.<br>Mañana, cuando salga el sol, llorará de envidia<br>por ella y por lo que pasó.<br>Esta noche hay miles de estrellas<br>y una mágica y radiante luna llena.<br>Dónde están los mares de verdad?<br>¿Y las tormentas de caricias, donde el huracán."
    },
    8: {
        nombre: "Amiga Mía",
        audio: "music/08 - Amiga Mía.mp3",
        letra: "Amiga mía, lo sé, sólo vives por él,<br>que lo sabe también, pero él no te ve<br>como yo, suplicarle a mi boca que diga<br>que me ha confesado entre copas,<br>que es con tu piel con quien sueña de noche<br>y que enloquece con cada botón que<br>te desabrochas pensando en sus manos.<br>Él no te ha visto temblar, esperando<br>una palabra, algún gesto un abrazo.<br>Él no te ve como yo suspirando,<br>con los ojitos abiertos de par en par<br>escucharme nombrarle.<br>¡Ay, amiga mía! Lo sé y él también.<br><br>Amiga mía, no sé qué decir,<br>ni qué hacer para verte feliz.<br>Ojalá pudiera mandar en el alma o en la libertad,<br>que es lo que a él le hace falta;<br>llenarte los bolsillos de guerras ganadas,<br>de sueños e ilusiones renovadas.<br>Yo quiero regalarte una poesía;<br>tú piensas que estoy dando las noticias.<br><br>Amiga mía, ojalá algún día escuchando mi canción,<br>de pronto, entiendas que lo que nunca quise<br>fue contar tu historia<br>porque pudiera resultar conmovedora.<br>Pero, perdona, amiga mía,<br>no es inteligencia, ni es sabiduría;<br>esta es mi manera de decir las cosas.<br>No es que sea mi trabajo, es que es mi idioma.<br><br>Amiga mía, princesa de un cuento infinito.<br>Amiga mía, tan sólo pretendo que cuentes conmigo.<br>Amiga mía, a ver si uno de estos días,<br>por fin aprendo a hablar<br>sin tener que dar tantos rodeos,<br>que toda esta historia me importa<br>porque eres mi amiga.<br><br>Amiga mía, lo sé, sólo vives por él,<br>que lo sabe también, pero él no te ve<br>como yo, suplicarle a mi boca que diga<br>que diga que me ha confesado entre copas,<br>que es con tu piel con quien sueña de noche...<br><br>Amiga mía, no sé qué decir,<br>ni qué hacer para verte feliz;<br>ojalá pudiera mandar en el alma o en la libertad,<br>que es lo que a él le hace falta;<br>llenarte los bolsillos de guerras ganadas,<br>de sueños e ilusiones renovadas.<br>Yo quiero regalarte una poesía;<br>tú piensas que estoy dando las noticias.<br><br>Amiga mía, princesa de un cuento infinito.<br>Amiga mía, tan sólo pretendo que cuentes conmigo.<br>Amiga mía, a ver si uno de estos días,<br>por fin aprendo a hablar<br>sin tener que dar tantos rodeos,<br>que toda esta historia me importa<br>porque eres mi amiga.<br><br>Amiga mía..."
    },
    9: {
        nombre: "Si Hay Dios...",
        audio: "music/09 - Si Hay Dios....mp3",
        letra: "Eh, si hay Dios seguramente entiende de emoción, si hay Dios...<br>Eh, si hay Dios, seguramente entiende de emoción, si hay Dios...<br><br>Podrás llevarte aquellos que me importan,<br>despojarme de mis ropas, desviarme de la luz.<br>Podrás llenar de oscuridad mis sueños,<br>podrás porque eres tú.<br><br>Podrás romper de nuevo el juramento,<br>deshaciendo las cadenas que te ataron una vez.<br>Pero dame tú el valor, que tengo miedo.<br>O puedes darme una esperanza<br>o, arrancarme, al fin, las ganas de seguir por ti<br>buscando entre mi almohada.<br>¿Qué es una Dama Blanca?<br><br>Eh, si hay Dios,<br>seguramente entiende de emoción, si hay Dios...<br><br>Podría haberte dicho que me importas.<br>Eso... Y un millón de cosas. Pude hacerlo<br>y no lo hice y no sé por qué.<br>Será porque es más fácil escribirlo<br>o demostrarlo, que<br>montar un numerito de esos de fatalidad,<br>según lo que establece el reglamento<br>del aparentar.<br><br>Podría haber llorado un mar de lágrimas<br>saladas, arrojarme a los abismos<br>y partirme en dos el alma, desatar la tempestad<br>y el huracán de mi garganta,<br>y confesar desesperado que no puedo con mi rabia.<br><br>Aunque mi actitud no es hoy tan evidente<br>no puedo sufrir más.<br>Que el dolor cuando es por dentro es más fuerte,<br>no se alivia con decírselo a la gente.<br><br>Lloraré... si sé llorar,<br>como el tímido rocío de un clavel en mi soledad.<br>Estaré...Todos se irán, ya lo sé,<br>a tu lado en cada golpe,<br>como lo hacen las orillas y la mar,<br>como lo hace el campo y el agua que lloverá.<br>Podría ser más educado<br>pero, el alma sólo entiende de emoción<br>y, si hay Dios, seguro entiende de emoción.<br><br>Eh, si hay Dios<br>seguramente entiende de emoción, si hay Dios...<br><br>Podría haber llorado un mar de lágrimas<br>saladas, arrojarme a los abismos<br>y partirme en dos el alma, desatar la tempestad<br>y el huracán de mi garganta,<br>y confesar desesperado que no puedo con mi rabia.<br><br>Aunque mi actitud no es hoy tan evidente,<br>no puedo sufrir más.<br>Que el dolor cuando es por dentro es más fuerte...<br><br>Lloraré...<br>Como el tímido rocío de un clavel, en soledad.<br>Estaré... todos se irán, ya lo sé,<br>a tu lado en cada golpe,<br>como lo hacen las orillas y la mar,<br>como lo hace el campo y el agua que lloverá.<br>Podría ser más educado<br>Pero, el alma sólo entiende de emoción<br>y, si hay Dios, seguro entiende de emoción.<br><br>Eh, si hay Dios, seguramente entiende de emoción, si hay Dios...<br>Eh, si hay Dios, seguramente entiende de emoción, si hay Dios...<br>Eh, si hay Dios, sea como sea simplemente amor, ¡ay Dios...!<br>Eh, si hay Dios, seguramente entiende de emoción, si hay Dios...<br>Eh, si hay Dios, seguramente entiende de tu amor, si hay Dios...<br>Eh, si hay Dios, seguramente entiende de emoción..."
    },
    10: {
        nombre: "Aquello Que Me Diste",
        audio: "music/10 - Aquello Que Me Diste.mp3",
        letra: "Inmensas tempestades, tu mano y la mía.<br>Tienes algo... no sé qué es.<br>Hay tanto de melódico en tu fantasía...<br>Y un toque de misterio, mi límite...<br>Conservo algún recuerdo que no debería,<br>lo sé, ¿qué puedo hacer?<br>A todos nos ocurre: la monotonía<br>nos gana la batalla, alguna vez, alguna vez...<br><br>Por eso, vida mía, por el día a día,<br>por enseñarme a ver el cielo más azul,<br>por ser mi compañera y darme tu energía;<br>no cabe en una vida mi gratitud<br>por aguantar mis malos ratos y manías,<br>por conservar secretos en ningún baúl...<br>Quiero ser por una vez,<br>capaz de ganar y de perder.<br><br>Perdona si me ves perder la compostura.<br>En serio te agradezco que hayas sido mía.<br>Si ves que mi canción acaso no resulta,<br>avísame y recojo la melancolía..., melancolía.<br><br>Te dejaré una ilusión,<br>envuelta en una promesa de eterna pasión;<br>una esperanza pintada en un mar de cartón;<br>un mundo nuevo que sigue donde un día lo pusiste.<br>Tú eres esa mujer<br>por quien me siento ese hombre capaz de querer,<br>viviendo cada segundo la primera vez,<br>sabiendo que me quisiste y todo aquello que me diste.<br><br>Conserva mi recuerdo de piratería.<br>Derrama los secretos: abre aquel baúl.<br>Sigamos siendo cómplices en compañía,<br>de aquello que me diste bajo el cielo azul.<br>Por aguantar mis malos ratos y manías,<br>por conservar secretos que me guardas tú.<br>Quiero ser por una vez,<br>capaz de ganar y de perder.<br><br>Perdón si alguna vez guardé la compostura.<br>No sabes lo que ha sido que hayas sido mía.<br>Comprendo que agotaste toda tu dulzura,<br>pero no me pidas, niña,<br>la melancolía..., melancolía.<br><br>Te dejaré una ilusión,<br>envuelta en una promesa de eterna pasión;<br>una esperanza pintada en un mar de cartón;<br>un mundo nuevo que existe donde un día lo pusiste.<br>Tú eres esa mujer<br>por quien me siento ese hombre capaz de querer,<br>vivo cada segundo la primera vez,<br>sabiendo que me quisiste<br>y todo aquello que me diste:<br><br>...un mundo nuevo que sigue<br>donde un día lo pusiste.<br>Tú eres esa mujer<br>por quien me siento ese hombre capaz de querer,<br>vivo cada segundo la primera vez,<br>sabiendo que me quisiste<br>y todo aquello que me diste."
    }

};

// Elementos del DOM
const modal = document.getElementById("modal"); // Modal donde se muestra la letra y el audio de la canción
const audioElement = document.getElementById("audio"); // Elemento de audio que se reproduce al seleccionar la canción
const modalContent = document.querySelector(".modal-content"); // Contenido del modal donde se inserta la letra y el audio

// Añadir evento a las canciones
document.querySelectorAll(".cancion").forEach(cancionElement => {// Añadir un evento de clic a cada elemento de canción
    cancionElement.addEventListener("click", () => {    // Remover la clase "selected" de todas las canciones previamente seleccionadas
        document.querySelectorAll(".track-header").forEach(header => {
            header.classList.remove("selected");
        });

        // Obtener el ID de la canción seleccionada desde el atributo "data-id"
        const id = cancionElement.getAttribute("data-id");
        if (canciones[id]) {
            // Si la canción existe en el objeto canciones, actualizar el contenido del modal
            modalContent.innerHTML = `
                <span class="close">&times;</span> <!-- Botón para cerrar el modal -->
                <h2>${canciones[id].nombre}</h2> <!-- Título de la canción -->
                <audio controls id="audio">
                    <source src="${canciones[id].audio}" type="audio/mp3"> <!-- Ruta del archivo de audio -->
                    Tu navegador no soporta este reproductor.
                </audio>
                <div id="letra">${canciones[id].letra}</div> <!-- Letra de la canción -->
            `;
            // Mostrar el modal con el contenido actualizado
            modal.style.display = "block";

            // Añadir la clase "selected" al header de la canción seleccionada para resaltar la canción
            cancionElement.querySelector(".track-header").classList.add("selected");

            // Actualizar el evento de cierre del modal
            const newCloseButton = document.querySelector(".close");
            newCloseButton.addEventListener("click", () => {
                // Cerrar el modal
                modal.style.display = "none";

                // Remover la clase "selected" de todas las canciones cuando se cierra el modal
                document.querySelectorAll(".track-header").forEach(header => {
                    header.classList.remove("selected");
                });
            });
        }
    });
});

// Cerrar la ventana modal al hacer clic fuera de ella
window.addEventListener("click", (event) => {
    if (event.target == modal) {
        // Si se hace clic fuera del modal, cerrarlo
        modal.style.display = "none";

        // Remover la clase "selected" de todas las canciones cuando se cierra el modal
        document.querySelectorAll(".track-header").forEach(header => {
            header.classList.remove("selected");
        });
    }
});

